### ISSUE TITLE
hasnt been updated in 6 days

### ISSUE THREAD

**Issue by CapCap** [qwertey6/SDC-SIS#1]
project dead? :-(

**Comment by ghost** [comment]
I made some changes to the code and proposed a new naming convention but I wouldn't want to go any further with the designs until we're agreed on whether the conventions work.
How about if there's a work meeting tomorrow we discuss this all in person there, or if there isn't an official one we can have our own meeting in AK or the library?

**Comment by ghost** [comment]
I don't understand GitHub mechanics yet which is why my changes aren't on here, but in the emails

**Comment by logansoldgit** [comment]
I'm gonna throw a bunch of shit on the project at once. Right now however I'm a bit busy. And regarding the naming conventions we probably can discuss those the next time we meet in person and decide on a completely concise method.

**Comment by CapCap** [comment]
We should start with a roadmap doc to try to get goals for each milestone release

**Comment by qwertey6** [comment]
Yeah we've been working on the actual system
